language: python

sudo: false

python:
  - "2.7"
  - "3.6"

install:
  - pip install 'requests>=2.7'
  - pip install 'u-msgpack-python>=2.4.1'
  - pip install 'numpy>=1.14.0'
  - pip install pandas
  - pip install coveralls
  - pip install vcrpy

script:
  - nosetests -v --with-coverage --cover-package=pyxylookup

after_success:
  - coveralls --verbose
